# Ubuntu as base image
FROM ubuntu

# Contact details
LABEL maintainer=rtaylo02

# Change directory into working directory. Folder helloapp is created if not exists.
WORKDIR /helloapp

# Copy source file (located in ./jar of local machine) into /helloapp inside the container
COPY ./jar/hello.jar /helloapp

# Run update and upgrade
RUN apt-get update
RUN apt-get upgrade

# Run openjdk17 and jre17 installation
RUN apt-get install openjdk-17-jdk openjdk-17-jre

# Run executable jar located in /helloapp/hello.jar
CMD [ "java", "-jar", "hello.jar" ]