# Ubuntu as base image
FROM ubuntu

# Contact details
LABEL maintainer=rtaylo02

# Set the working directory and change directory to it. Folder helloapp is created if not exists.
WORKDIR /helloapp

# Copy source file (located in ./jar of local machine) into /helloapp inside the container
COPY ./jar/helloapp-v2.jar /helloapp

# Run update and upgrade (with -y agreeing to all)
RUN apt-get update
RUN apt-get upgrade -y

# Run openjdk21 and jre21 installation (with -y agreeing to all)
RUN apt-get install openjdk-21-jdk openjdk-21-jre -y

# Run executable jar located in /helloapp/hello.jar
CMD [ "java", "-jar", "helloapp-v2.jar" ]
